#!/bin/bash

# Compile Program 04 - OTP

gcc -o keygen keygen.c -Wall

gcc -o otp_enc_d otp_enc_d.c otp_util.c -Wall
gcc -o otp_enc otp_enc.c otp_util.c -Wall

gcc -o otp_dec_d otp_dec_d.c otp_util.c -Wall
gcc -o otp_dec otp_dec.c otp_util.c -Wall


